name: Build web and deploy

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUTLER_API_KEY: ${{ secrets.BUTLER_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up emsdk
      run: web/setup.sh

    - name: Build and deploy eco2d
      run: web/deploy.sh
